const express = require("express");
const router = express.Router();

const filesRouter = require("./admin/files");
const adminAuthRouter = require("./admin/auth");
const managePagesRouter = require("./admin/managePages");
const menuRouter = require("./admin/menu");
const teamRouter = require("./admin/team");
const socialPlatForm = require("./admin/socialPlatform");
const agentRouter = require("./admin/agent");
const requestFileRouter = require("./admin/requestFile");
const contactRouter = require("./admin/contactUsEnquiry");
const blogsRouter = require("./admin/blogs");
const videosRouter = require("./admin/videos");
const ordersRouter = require("./admin/orders");
const usersRouter = require("./admin/users");
const dashboardRouter = require("./admin/dashboard");
const downloadPackagerRouter = require("./admin/downloadPackages");
const taxesRouter = require("./admin/taxes");
const siteOptionsRouter = require("./admin/siteOptions");
const filesUploadRouter = require("./admin/files-upload");
const reviewRouter = require("./admin/reviews");
const productRouter = require("./admin/products");
const socialPlatformRouter = require("./admin/socialPlatform");
const couponRouter = require("./admin/coupons");
const mediaRouter = require("./admin/media");
const walletRouter = require("./admin/wallet");
const jobRouter = require("./admin/jobs");
const settingsRouter = require("./admin/settings");
const currenciesRouter = require("./admin/currencies");
const courseRouter = require("./admin/course");
const modulesRouter = require("./admin/modules");
const rolesRouter = require("./admin/roles");
const aclRouter = require("./admin/acl");
const adminsRouter = require("./admin/admins");
const permissionsRouter = require("./admin/permissions");
const userAccountRouter = require('./admin/user/index');
const mailRouter = require('./admin/mailTemplates');
const leadsRouter = require("./admin/leads/index");
const uploadRouter = require("./admin/upload");
const reportsRouter = require("./admin/reports");
const excelReportsRouter = require("./admin/reportsExcel");
const apiManagerRouter = require("./admin/apiManager");
const cacheRouter = require("./admin/cache");
const transactionRouter = require("./admin/transactions");
const paymentGatewayRouter = require("./admin/payment-gateway");
const downloadsHistoryRouter  = require("./admin/downloadsHistory");
const downloadReportsRouter = require("./admin/downloadReports");
const bannerRouter = require("./admin/banner");
const telegramRouter = require("./admin/telegram");
const shiprocketRouter = require("./admin/shiprocket");
const bunnyRouter = require("./admin/bunny");
const telegramConfigRouter = require("./admin/telegramConfig");
const sitemapRouter = require("./admin/sitemap");
const dashboardAnalyticsRouter = require("./admin/dashboard-analytics");
const errorLogsRouter = require("./admin/errorLogs");
const notificationsRouter = require("./admin/notifications");
const socialLinksRouter = require("./admin/socialLinks");
const seoRouter = require("./admin/seo");
const databaseDumpRouter = require("./admin/databaseDump");
const googleSearchConsoleRouter = require("./admin/googleSearchConsole");
const offlinePaymentMethodsRouter = require("./admin/offlinePaymentMethods");
const suppliersRouter = require("./admin/suppliers");
const inventoryRouter = require("./admin/inventory");
const servicesRouter = require("./admin/services");
const invoicesRouter = require("./admin/invoices");
const activationKeysRouter = require("./admin/activationKeys");

// Routes

// Auth routes must come before any router that enforces admin auth globally.
// Otherwise requests like `/api/v1/admin/auth/login` would be intercepted by
// `filesRouter` (which applies `authenticateAdmin`) and return 401.
router.use("/auth", adminAuthRouter);
router.use("/", filesRouter);
router.use("/pages", managePagesRouter);
router.use("/menu", menuRouter);
router.use("/teams", teamRouter);
router.use("/social", socialPlatForm);
router.use("/agents", agentRouter);
router.use("/request-file", requestFileRouter);
router.use("/leads", contactRouter);
router.use("/blogs", blogsRouter);
router.use("/videos", videosRouter);
router.use("/orders", ordersRouter);
router.use("/shiprocket", shiprocketRouter);
router.use("/bunny", bunnyRouter);
router.use("/users", usersRouter);  
router.use("/users/account", userAccountRouter);
router.use("/wallet", walletRouter);
router.use("/dashboard", dashboardRouter);
router.use("/download-packages", downloadPackagerRouter);
router.use("/taxes", taxesRouter);
router.use("/settings", siteOptionsRouter);
router.use("/files", filesUploadRouter);
router.use("/coupon-discounts", couponRouter);
router.use("/reviews", reviewRouter);
router.use("/products", productRouter);
router.use("/social-platforms", socialPlatformRouter);
router.use("/media", mediaRouter);
router.use("/jobs", jobRouter);
router.use("/currencies", currenciesRouter);
router.use("/courses", courseRouter);
router.use("/modules", modulesRouter);
router.use("/roles", rolesRouter);
router.use("/permissions", permissionsRouter);
router.use("/acl", aclRouter);
router.use("/admins", adminsRouter);
router.use("/email-templates", mailRouter);
router.use("/leads", leadsRouter);
router.use("/reports", reportsRouter);
router.use("/reports/download/excel", excelReportsRouter);
router.use("/api-manager", apiManagerRouter);
router.use("/cache", cacheRouter);
router.use("/transactions", transactionRouter);
router.use("/payment-gateways", paymentGatewayRouter);
router.use("/downloads-history", downloadsHistoryRouter);
router.use("/download-reports", downloadReportsRouter);
router.use("/banner",  bannerRouter);
router.use("/telegram", telegramRouter);
router.use("/telegram-config", telegramConfigRouter);
router.use("/sitemap", sitemapRouter);
router.use("/dashboard-analytics", dashboardAnalyticsRouter);
router.use("/error-logs", errorLogsRouter);
router.use("/notifications", notificationsRouter);
router.use("/social-links", socialLinksRouter);
router.use("/seo", seoRouter);
router.use("/database-dump", databaseDumpRouter);
router.use("/google-search-console", googleSearchConsoleRouter);
router.use("/offline-payment-methods", offlinePaymentMethodsRouter);
router.use("/suppliers", suppliersRouter);
router.use("/inventory", inventoryRouter);
router.use("/services", servicesRouter);
router.use("/invoices", invoicesRouter);
router.use("/activation-keys", activationKeysRouter);

module.exports = router;